version = 0.1
[default.deploy.parameters]
stack_name = "hello-world-step-function"
resolve_s3 = true
s3_prefix = "hello-world-step-function"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Name=\"hello-world\" EnvironmentType=\"test\" Owner=\"Platform\""
image_repositories = []
